// Code generated by hand, DO NOT EDIT.

package a

func gentests() {
	a, b, c := "a", "b", "c"

	abc(a, b, c) // good
	abc(a, a, c) // dup name is visible
	abc(b, a, c) // ignored
}

var _ = gentests
